services:
  cb-node1:
    image: couchbase:community
    container_name: cb-node1
    ports:
      - "8091-8096:8091-8096"  # Web UI and service ports
      - "11210-11211:11210-11211"  # Data access ports
    # Optional: Add volumes for persistence
    # volumes:
    #   - ./cb-node1-data:/opt/couchbase/var
